# -*- coding: utf-8 -*-
"""ex_polimorfismo_veiculo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1deBXgXgPjcc12ygj_NgxDLL7mhFBzSGe
"""


class Veiculo:
    def __init__(self, cor, marca, modelo, qtd_tanque):
        self.cor = cor
        self.marca = marca
        self.modelo = modelo
        self.qtd_tanque = qtd_tanque

    def abastecer(self, litros):
        print('Tentando abastecer ' + str(litros) + ' litros')
        if self.qtd_tanque + litros > self.get_limite_litros_tanque():
            print('Capacidade máxima alcançada, foi possível abastecer:', str(
                self.get_limite_litros_tanque() - self.qtd_tanque), 'litros')
            self.qtd_tanque = self.get_limite_litros_tanque()
        else:
            self.qtd_tanque += litros

    def imprime(self):
        print('O veículo ', self.get_marca(), self.get_modelo(),
              'de cor ', self.get_cor(),
              'tem', self.get_qtd_tanque(), 'litros no tanque')

    def get_limite_litros_tanque(self):
        return 100

    def get_cor(self):
        return self.cor

    def set_cor(self, cor):
        self.cor = cor

    def get_marca(self):
        return self.marca

    def set_marca(self, marca):
        self.marca = marca

    def get_modelo(self):
        return self.modelo

    def set_modelo(self, modelo):
        self.modelo = modelo

    def get_qtd_tanque(self):
        return self.qtd_tanque

    def set_qtd_tanque(self, qtd_tanque):
        self.qtd_tanque = qtd_tanque
